blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('index/', views.IndexView.as_view(), name = 'index'),
    path('', views.IndexView.as_view(), name = 'index'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name = 'detail'),
    path('archives/<int:year>/<int:month>', views.ArchivesView.as_view(), name = 'archives'),
    path('category/<int:pk>', views.CategoryView.as_view(), name = 'category'),
    path('tag/<int:pk>', views.TagView.as_view(), name = 'tag'),
    path('blog/', views.BlogView.as_view(), name = 'blog'),
    # path('contact/', views.Contact, name = 'contact'),
    path('about/', views.About, name = 'about'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.feeds import AllPostsRssFeed


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    path('all/rss/', AllPostsRssFeed(), name = 'rss'),
    path('search/', include('haystack.urls')),
    path('', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),

]

comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/post/<int:post_pk>', views.post_comment, name = 'post_comment'),
    path('contact/', views.post_contact, name = 'post_contact')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('users/register/', views.register, name = 'register')
]

blog/models.py
from django.db import models
from users.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags

# Create your models here.
class Category(models.Model):
    #分类数据库模型
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Tag(models.Model):
    #标签数据库模型
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Post(models.Model):
    #文章数据库模型

    # 文章标题
    title = models.CharField(max_length=70)

    # 文章正文，我们使用了 TextField。
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    body = models.TextField()

    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(max_length=200, blank=True)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)  #一对多
    tags = models.ManyToManyField(Tag, blank=True)   #多对多

    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs = {'pk' : self.pk})

    #内部类，通过指定属性规定该类的特性
    class Meta:
        ordering = ['-created_time']
    #复写save方法
    def save(self, *args, **kwargs):
        if not self.excerpt:
            #初始化markdown类
            md = markdown.Markdown(
                extension_configs=[
                    'markdown.extensions.extra',
                    'markdown.extensions.codehilite'
                ] )
            #先将Markdown文本渲染成HTML文本, strip_tags去掉HTML标签
            self.excerpt = strip_tags(md.convert(self.body))[:180]
        #调用父类的save方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

comments/models.py
from django.db import models
# Create your models here.

class Comment(models.Model):
    name = models.ForeignKey('users.User', on_delete = models.CASCADE)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)
    #当打印类实例时调用
    def __str__(self):
        return self.text[:20]
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
    message = models.TextField()
    drop_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message[:20]

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Post, Category, Tag
import markdown
from comments.forms import CommentForm, ContactForm
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.db.models import Q
# Create your views here.

class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 3
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        paginator_data = self.pagination_data(paginator, page, is_paginated)
        context.update(paginator_data)
        return context
    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}
        #左侧连续页面
        left = []
        right = []
        #左侧省略号
        left_has_more = False
        right_has_more = False
        #第一页页码
        first = False
        last = False
        #当前页码
        page_number = page.number
        #总页数
        total_pages = paginator.num_pages
        #页面列表[1, 2, 3, 4]
        page_range = paginator.page_range
        #如果有足够页面，显示三页连续,跟省略号
        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left':left,
            'right':right,
            'left_has_more':left_has_more,
            'right_has_more':right_has_more,
            'first':first,
            'last':last
        }
        return data
class BlogView(IndexView):
    template_name = 'blog/blog.html'
class ArchivesView(IndexView):
    #覆写父类方法，按条件查找
    def get_queryset(self):
        return super(ArchivesView, self).get_queryset().filter(created_time__year=self.kwargs.get('year'), created_time__month=self.kwargs.get('month'))

class CategoryView(IndexView):
    #这里的pk为分类对应的id号并非文章
    def get_queryset(self):
        #通过分类的id号获得分类对象
        cate = get_object_or_404(Category, pk = self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category = cate)

class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk = self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags = tag)

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'
    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 当 get 方法被调用后，才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return  response
    def get_object(self, queryset=None):
         md = markdown.Markdown(extensions=[
                                      'markdown.extensions.extra',
                                      #代码高亮
                                      'markdown.extensions.codehilite',
                                      #标题标签'markdown.extensions.toc',
                                       TocExtension(slugify=slugify),
                                    ])
         post = super(PostDetailView, self).get_object(queryset=None)
         post.body = md.convert(post.body)
         post.toc = md.toc
         return post
    def get_context_data(self, **kwargs):
        # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板。
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form':form,
            'comment_list':comment_list
        })
        return context
    # post = get_object_or_404(Post, pk = pk)
    # #阅读量 +1
    # post.increase_views()
    # #将MarkDown渲染为html文本
    # post.body = markdown.markdown(post.body,
    #                               extensions=[
    #                                   'markdown.extensions.extra',
    #                                   'markdown.extensions.codehilite',
    #                                   'markdown.extensions.toc',
    #                                 ])
    # form = CommentForm()
    # comment_list = post.comment_set.all()
    # context = {
    #     'post' : post,
    #     'form' : form,
    #     'comment_list' : comment_list
    # }
    # return render(request, 'blog/detail.html', context = context)

# def Contact(request):
#     form = ContactForm()
#     context = {'form' : form}
#     return render(request,'blog/contact.html', context = context)

def About(request):
    return render(request, 'blog/about.html')

templates/blog/about.html
{% extends 'base2.html' %}
{% load staticfiles %}
{% block main %}
    <h1 class="page-title">关于本站</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="{% static 'blog/images/log.png' %}" alt="Developer Image">
                                </figure>
								<p align="center">个人小站，多多包涵。</p>
								<p align="center">Go big or go home.</p>

                                <!--
								<div class="height-40px"></div>
                                <h2 class="title text-center">社交</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							-->
							</div>
						</article>

{% endblock %}

templates/blog/blog.html
{% extends 'base2.html' %}

{% block main %}
{% for post in post_list %}
                <!-- pk 是 primary key 的缩写，即 post 对应于数据库中记录的 id 值-->
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}        ...</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                    <!--当post-list为空时执行-->
                {% empty %}
                    <div class="no-post">暂时还没有发布的文章！</div>
                    <!--表示结束循环-->
                {% endfor %}

                <!-- 简单分页效果-->
                <div class="text-center">
                    {% if is_paginated %}
                    <div class="pagination">
                        {% if  first %}
                            <a href="?page=1">1</a>
                        {% endif %}
                        {% if left %}
                            {% if left_has_more %}
                                <span>...</span>
                            {% endif %}
                            {% for i in left %}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endfor %}
                        {% endif %}
                        <a class="current-page" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                        {% if right %}
                            {% for i in right %}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endfor %}
                            {% if right_has_more %}
                                <span>...</span>
                            {% endif %}
                            {% if last %}
                                <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                            {% endif %}
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
{% endblock %}

templates/blog/contact.html
{% extends 'base2.html' %}
{% block main %}
                    <h1 class="page-title">投稿</h1>
						<article class="post">
							<div class="entry-content clearfix">

                                <form action="{% url 'comments:post_contact' %}" method="post" class="contact-form">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6 col-md-offset-3">
                                        <label for="{{ form.name.id_for_label }}">作者：</label>
                                        {{ form.name }}
                                        {{ form.name.errors }}
                                        <label for="{{ form.email.id_for_label }}">电子邮箱：</label>
                                        {{ form.email }}
                                        {{ form.email.errors }}
                                        <label for="{{ form.subject.id_for_label }}">主题：</label>
                                        {{ form.subject }}
                                        {{ form.subject.errors }}
                                        <label for="{{ form.message.id_for_label }}">内容：</label>
                                        {{ form.message }}
                                        {{ form.message.errors }}
                                        <center><button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>提交</span></button></center>
                                    </div>
                                </div>    <!-- row -->
                                </form>

							</div>
						</article>
{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <!--任何的 HTML 代码在 Django 的模板中都会被转义,safe标签解除转义-->
                       {{ post.body|safe }}
                        <div class="widget-tag-cloud">
                            <ul>
                                标签：
                                {% for tag in post.tags.all %}
                                    <li><a href="{% url 'blog:tag' tag.pk %}"># {{ tag.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    {% if user.is_authenticated %}
                        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="{{ form.text.id_for_label }}">评论：</label>
                                    {{ form.text }}
                                    {{ form.text.errors }}
                                    <button type="submit" class="comment-btn">发表</button>
                                </div>
                            </div>    <!-- row -->
                        </form>
                    {% else %}
                         <p>你还没有登录，请
                            <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">登录</a></button>
                            或者
                            <button class="btn btn-default"><a href="{% url 'users:register' %}?next={{ request.path }}">注册</a></button>
                        </p>
                    {% endif %}
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            暂无评论!
                            {% endfor %}
                        </ul>
                    </div>
                </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    {{ post.toc|safe }}
                </div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
                <!-- pk 是 primary key 的缩写，即 post 对应于数据库中记录的 id 值-->
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}...</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                    <!--当post-list为空时执行-->
                {% empty %}
                    <div class="no-post">暂时还没有发布的文章！</div>
                    <!--表示结束循环-->
                {% endfor %}

                <!-- 简单分页效果-->
                <div class="text-center">
                    {% if is_paginated %}
                    <div class="pagination">
                        {% if  first %}
                            <a href="?page=1">1</a>
                        {% endif %}
                        {% if left %}
                            {% if left_has_more %}
                                <span>...</span>
                            {% endif %}
                            {% for i in left %}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endfor %}
                        {% endif %}
                        <a class="current-page" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                        {% if right %}
                            {% for i in right %}
                                <a href="?page={{ i }}">{{ i }}</a>
                            {% endfor %}
                            {% if right_has_more %}
                                <span>...</span>
                            {% endif %}
                            {% if last %}
                                <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                            {% endif %}
                        {% endif %}
                    </div>
                    {% endif %}
                </div>

{% endblock main %}

templates/blog/register.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>注册</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h1><a href="{% url 'blog:index' %}">BigOrange</a></h1>
                <h3>注册</h3>
                <form class="form" action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">注册</button>
                    <input type="hidden" name="next" value="{{ next }}"/>
                </form>
                <div class="flex-center top-gap text-small">
                    <a href="{% url 'login' %}?next={{ next }}">已有账号登录</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>