blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('index/', views.IndexView.as_view(), name = 'index'),
    path('', views.IndexView.as_view(), name = 'index'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name = 'detail'),
    path('archives/<int:year>/<int:month>', views.ArchivesView.as_view(), name = 'archives'),
    path('category/<int:pk>', views.CategoryView.as_view(), name = 'category'),
    path('tag/<int:pk>', views.TagView.as_view(), name = 'tag'),
    path('blog/', views.BlogView.as_view(), name = 'blog'),
    # path('contact/', views.Contact, name = 'contact'),
    path('about/', views.About, name = 'about'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.feeds import AllPostsRssFeed


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    path('all/rss/', AllPostsRssFeed(), name = 'rss'),
    path('search/', include('haystack.urls')),
    path('', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),

]

comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/post/<int:post_pk>', views.post_comment, name = 'post_comment'),
    path('contact/', views.post_contact, name = 'post_contact')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('users/register/', views.register, name = 'register')
]

templates/base.html
<!DOCTYPE html>
<!--模板标签(具有类似函数的功能)-->
{% load staticfiles %}
{% load blog_tags %}
{% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
{% endif %}
<html>
<head>
    <title>BigOrange &amp; Blog</title>
    <style>
        span.highlighted{
            color: #00CCFF;
        }
    </style>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/vs.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/page.css' %}">

    <!-- js -->
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>BigOrange</b> &amp; Blog</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:blog' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            {% if user.is_authenticated %}
                                <li class="cl-effect-11"><a href=""  data-hover="{{ request.user }}">{{ request.user }}</a></li>
                                <li class="cl-effect-11"><a href="{% url 'comments:post_contact' %}" data-hover="投稿">投稿</a></li>
                                <li class="cl-effect-11"><a href="{% url 'logout' %}?next={{ request.path }}" data-hover="注销">注销</a></li>
                                <li class="cl-effect-11"><a href="{% url 'password_change' %}" data-hover="修改密码">修改密码</a></li>
                            {% else %}
                                <li class="cl-effect-11"><a href="{% url 'login' %}?next={{ request.path }}" data-hover="登录">登录</a></li>
                                <li class="cl-effect-11"><a href="{% url 'users:register' %}?next={{ request.path }}" data-hover="注册">注册</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">陈西成的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% get_recent_posts as recent_posts_list %}
                        {% for post in recent_posts_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章！
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% archives as data_list %}
                        {% for data in data_list %}
                        <li>
                            <a href="{% url 'blog:archives' data.year data.month %}">{{ data.year }} 年 {{ data.month }} 月</a>
                        </li>
                        {% empty %}
                        暂无归档
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% get_categories as categories_list %}
                        {% for categories in categories_list %}
                        <li>
                            <a href="{% url 'blog:category' categories.pk %}">{{ categories.name }}<span class="post-count"> ({{ categories.num_posts }})</span></a>
                        </li>
                        {% empty %}
                        暂无分类
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% get_tag as tags %}
                        {% for tag in tags %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        暂无标签
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 2020 <a href="" title="网页模板" target="_blank">BigOrange Blog</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
            <li><a href="{% url 'blog:blog' %}" data-hover="博客">博客</a></li>
            <li><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
            {% if user.is_authenticated %}
                <li><a href="" data-hover="{{ request.user }}">{{ request.user }}</a></li>
                <li><a href="{% url 'comments:post_contact' %}" data-hover="投稿">投稿</a></li>
                <li><a href="{% url 'logout' %}?next={{ request.path }}" data-hover="注销">注销</a></li>
                <li><a href="{% url 'password_change' %}" data-hover="修改密码">修改密码</a></li>
            {% else %}
                <li><a href="{% url 'login' %}?next={{ request.path }}" data-hover="登录">登录</a></li>
                <li><a href="{% url 'users:register' %}?next={{ request.path }}" data-hover="注册">注册</a></li>
            {% endif %}
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

templates/base2.html
<!DOCTYPE html>
<!--模板标签(具有类似函数的功能)-->
{% load staticfiles %}
{% load blog_tags %}
{% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
{% endif %}
<html>
<head>
    <title>BigOrange &amp; Blog</title>
    <style>
        span.highlighted{
            color: #00CCFF;
        }
    </style>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/vs.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/page.css' %}">

    <!-- js -->
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

</head>

<body>
		<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>BigOrange</b> &amp; Blog</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:blog' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            {% if user.is_authenticated %}
                                <li class="cl-effect-11"><a href="" data-hover="{{ request.user }}">{{ request.user }}</a></li>
                                <li class="cl-effect-11"><a href="{% url 'comments:post_contact' %}" data-hover="投稿">投稿</a></li>
                                <li class="cl-effect-11"><a href="{% url 'logout' %}?next={{ request.path }}" data-hover="注销">注销</a></li>
                                <li class="cl-effect-11"><a href="{% url 'password_change' %}" data-hover="修改密码">修改密码</a></li>
                            {% else %}
                                <li class="cl-effect-11"><a href="{% url 'login' %}?next={{ request.path }}" data-hover="登录">登录</a></li>
                                <li class="cl-effect-11"><a href="{% url 'users:register' %}?next={{ request.path }}" data-hover="注册">注册</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">陈西成的博客</a></div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
                        {% block main %}
                        {% endblock %}
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
            <div class="container">
            <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 2020 <a href="" title="网页模板" target="_blank">BigOrange Blog</a>
                </p>
            </div>
            </div>
            </div>
        </footer>

		<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
            <li><a href="{% url 'blog:blog' %}" data-hover="博客">博客</a></li>
            <li><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
            {% if user.is_authenticated %}
                <li><a href="" data-hover="{{ request.user }}">{{ request.user }}</a></li>
                <li><a href="{% url 'comments:post_contact' %}" data-hover="投稿">投稿</a></li>
                <li><a href="{% url 'logout' %}?next={{ request.path }}" data-hover="注销">注销</a></li>
                <li><a href="{% url 'password_change' %}" data-hover="修改密码">修改密码</a></li>
            {% else %}
                <li><a href="{% url 'login' %}?next={{ request.path }}" data-hover="登录">登录</a></li>
                <li><a href="{% url 'users:register' %}?next={{ request.path }}" data-hover="注册">注册</a></li>
            {% endif %}
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>